//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourManagementSystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TourDbEntities : DbContext
    {
        public TourDbEntities()
            : base("name=TourDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Excursion> Excursions { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Guard> Guards { get; set; }
        public virtual DbSet<Nutrition> Nutritions { get; set; }
        public virtual DbSet<Policy> Policies { get; set; }
        public virtual DbSet<Position> Positions { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Tour> Tours { get; set; }
        public virtual DbSet<Tours_Cities> Tours_Cities { get; set; }
        public virtual DbSet<Tours_Destinations> Tours_Destinations { get; set; }
        public virtual DbSet<Tours_Excursions> Tours_Excursions { get; set; }
        public virtual DbSet<Tours_Policies> Tours_Policies { get; set; }
        public virtual DbSet<Tours_Services> Tours_Services { get; set; }
    }
}
