//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tours_Cities
    {
        public int ID { get; set; }
        public int TourId { get; set; }
        public int CityId { get; set; }
        public int Deleted { get; set; }
    
        public virtual City City { get; set; }
        public virtual Tour Tour { get; set; }
    }
}
