//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tour
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tour()
        {
            this.Tours_Cities = new HashSet<Tours_Cities>();
            this.Tours_Destinations = new HashSet<Tours_Destinations>();
            this.Tours_Excursions = new HashSet<Tours_Excursions>();
            this.Tours_Policies = new HashSet<Tours_Policies>();
            this.Tours_Services = new HashSet<Tours_Services>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int CategoryId { get; set; }
        public int GuardId { get; set; }
        public int NutritionId { get; set; }
        public System.DateTime BeginDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public decimal Price { get; set; }
        public string Description { get; set; }
        public bool IsHotelIncluded { get; set; }
        public bool IsFotoSessionIncluded { get; set; }
        public int Deleted { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Guard Guard { get; set; }
        public virtual Nutrition Nutrition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tours_Cities> Tours_Cities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tours_Destinations> Tours_Destinations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tours_Excursions> Tours_Excursions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tours_Policies> Tours_Policies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tours_Services> Tours_Services { get; set; }
    }
}
